# NODES

row_drug:
    is_a: drug 
    represented_as: node
    label_in_input : row_drug
    properties:
        canonicalSmiles: str
        inchiKey: str
        drugType: str
        blackBoxWarning: bool
        drug_name: str
        yearOfFirstapproval: str
        maximumClinicalTrialPhase: str
        hasBeenWithdrawn: bool
        isApproved: bool
        tradeName: str
        synonym: str
        references: str
        description: str
        data_source: str

# parent drug:
#     is_a: drug
#     represented_as: node
#     label_in_input : parent_drug
#     properties:
#         canonicalSmiles: str
#         inchiKey: str
#         drugType: str
#         blackBoxWarning: bool
#         drug_name: str
#         yearOfFirstapproval: str
#         maximumClinicalTrialPhase: str
#         hasBeenWithdrawn: bool
#         isApproved: bool
#         tradeName: str
#         synonym: str
#         references: str
#         description: str

# child drug:
#     is_a: drug
#     represented_as: node
#     label_in_input : chid_drug
#     properties:
#         canonicalSmiles: str
#         inchiKey: str
#         drugType: str
#         blackBoxWarning: bool
#         drug_name: str
#         yearOfFirstapproval: str
#         maximumClinicalTrialPhase: str
#         hasBeenWithdrawn: bool
#         isApproved: bool
#         tradeName: str
#         synonym: str
#         references: str
#         description: str

drug:
    # is_a: drug 
    represented_as: node
    label_in_input : drug
    properties:
        canonicalSmiles: str
        inchiKey: str
        drugType: str
        blackBoxWarning: bool
        drug_name: str
        yearOfFirstapproval: str
        maximumClinicalTrialPhase: str
        hasBeenWithdrawn: bool
        isApproved: bool
        tradeName: str
        synonym: str
        references: str
        description: str
        data_source: str
        
gene:
    represented_as: node
    label_in_input: gene
    properties:
        gene_summary: str
        hugoSymbol: str
        name: str
        data_source: str

protein:
    represented_as: node
    label_in_input: protein
    properties:
        data_source: str

# EDGES

drug_has_target:
    is_a: drug to gene association
    represented_as: edge
    label_in_input: drug_has_target
    properties:
        data_source: str

# subclass of:
#     represented_as: edge
#     label_in_input : subclass_of

# superclass of:
#     represented_as: edge
#     label_in_input : superclass_of
#     properties:
#         actionType: str
#         mechanism_of_action: str
#         # references: str

transcript_to_gene_relationship:
    is_a : transcript to gene relationship
    represented_as: edge
    input_label: transcript_to_gene_relationship
    properties:
        data_source: str

